### DISCUSSION TITLE
Show & Tell: Raspberry PI 3 B+ Network & Nginx Configuration

### DISCUSSION THREAD

**Discussion by JasonKleban** [scottlamb/moonfire-nvr#118] [Show and tell]
I want to share this netplan & nginx configuration so far.  It is incomplete.

![rpi3b+, usb drive dock, PoE injector, and HNC304-WDA (manufacturer unknown)](https://user-images.githubusercontent.com/17498172/84596329-05a8d980-ae2b-11ea-99d3-b19c686edd72.png)
_rpi3b+, usb drive dock, PoE injector, and HNC304-WDA (manufacturer unknown).  Ethernet is for the camera(s) LAN and onboard wifi is for the external WAN._

I started with Ubuntu 20 64-bit for Raspberry PI image.  I [removed snapd](https://askubuntu.com/questions/1035915/how-to-remove-snap-store-from-ubuntu/1035917#1035917) for boot speed, [added zram-config](https://github.com/scottlamb/moonfire-nvr/issues/85#issuecomment-643671742) for eventual memory issues, and [removed cloud-init](https://askubuntu.com/questions/539277/how-to-get-rid-of-cloud-init/1068584#1068584) and replaced it with the following Netplan .yaml configuration and added `sudo apt install avahi-daemon` for zeroconf mdns:

```
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 192.168.1.1/24
            dhcp4: false
    wifis:
        wlan0:
            optional: true
            dhcp4: true
            access-points:
                "*****":
                    password: "*****"
```

I got moonfire working on port 8080 by the guides, but I want to also have access to the camera configuration directly.  I think I could use a network bridge and firewall or port forwarding, but it seems that it will be easier to use Nginx.  [As of 10 years ago unfortunately](https://stackoverflow.com/questions/775233/how-to-route-all-subdomains-to-a-single-host-using-mdns), avahi seems to not support subdomains (aliasing) even though they seem easy to support in Nginx and would be the most user-friendly in my opinion (assuming that rtsp streams can be proxied with nginx too) compared to port numbers, and the most compatible compared to "virtual directory" mounting (by path).  RTSP wouldn't work yet and I haven't really tried moonfire yet beyond being able to reach the page, but being able to configure the camera directly instead of having to physically plug in is nice.  dhcp with camera hostnames mapped to a subdomain automatically would be even nicer - although every camera would need some kind of static configuration initially anyway...

```
# No catchall.  Exact matches only
server {
    listen      80 default_server;
    server_name "";
    return      444;
}

# server_name won't work because of avahi/mdns "aliasing" limitations?  But ports will.
server {
        listen  81;
        server_name moonfire.*;
        location / {
            proxy_pass       http://127.0.0.1:8080;
        }
}

server {
        listen  82;
        server_name camera1.*;
        location / {
            proxy_pass       http://192.168.1.64:80;
        }
}
```

Thoughts on this configuration?
