### ISSUE TITLE
Support docker-compose deployment

### ISSUE THREAD

**Issue by pbrenna** [scottlamb/moonfire-nvr#265]
Deploying with docker-compose can be quite useful.

It might be beneficial to include this alternate method in the install instructions.

`docker-compose.yml` :

```yaml
version: '3.5'
services:
  moonfire:
    image: "moonfire-nvr:latest"
    volumes:
     - ./moonfire-nvr:/var/lib/moonfire-nvr
     - ./moonfire-nvr.toml:/etc/moonfire-nvr.toml:ro
    # Add additional mount lines here for each sample file directory
    # outside of /var/lib/moonfire-nvr, e.g.:
    # - /media/nvr/sample:/media/nvr/sample
    user: "${UID}:${GID}"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      TZ: ":${TZ}"
      RUST_BACKTRACE: 1
    logging:
      driver: journald
      options:
        tag: moonfire-nvr
    entrypoint: ["moonfire-nvr", "run"]
```
`.env` :
```bash
GID=1007
UID=1007
TZ=Europe/Amsterdam
```

`/usr/local/bin/nvr`:
```bash
#!/bin/bash
set -e
cd /path/to/docker-compose/dir
docker-compose run --rm -ti --entrypoint=/bin/bash moonfire "-c" 'moonfire-nvr "$@"' --  "$@"
```
Drawbacks: GID and UID can't be filled in programmatically (but could be written in the env file at the time of user creation).
